### ISSUE TITLE
Broken Oscilloscope example

### ISSUE THREAD

**Issue by jaredl7** [pyacq/pyacq#64]
Hello,

The current version of the library does not work with the Oscilloscopes example `pyacq/examples/pyaudio_oscope_local.py` as the following error is raised:

```
Traceback (most recent call last):
  File "pyaudio_oscope_local.py", line 8, in <module>
    from pyacq.devices.audio_pyaudio import PyAudio
  File "/home/jared/.virtualenvs/Python35/lib/python3.5/site-packages/pyacq/__init__.py", line 9, in <module>
    from .core import *
  File "/home/jared/.virtualenvs/Python35/lib/python3.5/site-packages/pyacq/core/__init__.py", line 8, in <module>
    from .node import Node, WidgetNode
  File "/home/jared/.virtualenvs/Python35/lib/python3.5/site-packages/pyacq/core/node.py", line 9, in <module>
    from .stream import OutputStream, InputStream
ImportError: No module named 'pyacq.core.stream'
```

Looking into it, it appears that error arises from the fact that the subpackage `'pyacq.core.stream'` isn't included in `setup.py`. Uninstalling `pyacq`, then adding that subpackage to the `packages` variable on line 18 fixes the problem in a clean install.

**Comment by samuelgarcia** [comment]
Closed by #68.
